"use client";

import { useState } from "react";

function Arrow({ diagonal = false }: { diagonal?: boolean }) {
  return <svg aria-hidden="true" viewBox="0 0 20 20" width="16" height="16"><path d={diagonal ? "M5 15 15 5M8 5h7v7" : "M4 10h11M11 6l4 4-4 4"} fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="1.5" /></svg>;
}

function NaroMark() {
  return <a className="brand" href="/" aria-label="Naro home"><svg viewBox="0 0 28 28" aria-hidden="true"><path d="M5 21V7l9 9 9-9v14" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.4" /><path d="m5 7 9-4 9 4" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.4" /></svg><span>NARO</span></a>;
}

export function SiteHeader({ compact = false }: { compact?: boolean }) {
  const [notice, setNotice] = useState(false);
  return <><header className={compact ? "site-header compact" : "site-header"}><NaroMark /><nav aria-label="Primary navigation"><a href="/#intelligence">Intelligence</a><a href="/#controls">Controls</a><a href="/vaults">Vaults</a><a href="/#transparency">Transparency</a></nav><button className="wallet-button" onClick={() => setNotice(true)}><span className="status-dot" /> Connect wallet</button></header>{notice && <div className="toast" role="status"><span className="toast-icon">↗</span><span><b>Wallet selection</b><small>Choose a vault to connect the correct wallets.</small></span><button aria-label="Dismiss notification" onClick={() => setNotice(false)}>×</button></div>}</>;
}

function AgentCore() {
  const venues = [
    ["01", "Solv · solvBTC", "6.16%", "94", "SELECTED"],
    ["02", "Lombard · LBTC", "4.84%", "87", "CURRENT"],
    ["03", "Babylon · BTC", "3.21%", "91", "STANDBY"],
    ["04", "Pendle · PT-LBTC", "7.42%", "73", "REJECTED"],
  ];
  return <div className="agent-stage intelligence-stage" aria-label="Naro AI comparing approved Bitcoin yield venues and preparing a policy-bound rebalance">
    <div className="stage-grid" /><div className="stage-scan" />
    <div className="neural-field" aria-hidden="true"><i /><i /><i /><i /><i /><i /></div>
    <div className="ai-stage-header"><span><i className="live-dot" /> NARO YIELD INTELLIGENCE</span><small>MULTI-ASSET MODEL 1.4 · EPOCH 21480</small></div>
    <div className="mandate-strip"><span className="mandate-asset">₿</span><div><small>ACTIVE BLUECHIP MANDATE</small><b>BTC · Capital preservation</b></div><div className="mandate-rules"><span>Risk ≤ 25</span><span>Liquidity ≥ 14%</span><span>Approved venues only</span></div><em>CIARA / ACTIVE</em></div>
    <div className="ai-console-grid">
      <section className="yield-radar"><div className="console-title"><span>RISK-ADJUSTED OPPORTUNITY RANKING</span><small>NET APY</small><small>SCORE</small></div>{venues.map(([rank, venue, apy, score, status]) => <div className={`venue-row venue-${status.toLowerCase()}`} key={venue}><span>{rank}</span><div><b>{venue}</b><small>{status}</small></div><strong>{apy}</strong><em>{score}</em></div>)}</section>
      <section className="decision-engine"><div className="decision-head"><span>AI DECISION · 08F4</span><i>CONFIDENCE 94%</i></div><div className="decision-core"><span className="thinking-ring" /><small>OPTIMAL ACTION</small><strong>Reallocate<br />12.5 BTC</strong><p><span>Lombard</span><i>→</i><span>Solv</span></p></div><div className="decision-delta"><span>EXPECTED APY LIFT</span><b>+132 <small>BPS</small></b></div></section>
    </div>
    <div className="execution-flow"><div><small>01 · OBSERVE</small><b>42 signals normalized</b></div><i /><div><small>02 · REASON</small><b>16,240 paths simulated</b></div><i /><div className="flow-active"><small>03 · VERIFY</small><b>4/4 policy gates passed</b></div><i /><div><small>04 · EXECUTE</small><b>Route prepared</b></div></div>
    <div className="agent-status"><span className="live-dot" /> COORDINATOR ONLINE <i>Cross-protocol optimization · every action mandate-bound</i></div>
  </div>;
}

const controls = [["01", "Allocation", "Strategy and venue caps"],["02", "Leverage", "Hard exposure ceilings"],["03", "Liquidity", "Redemption reserves"],["04", "Counterparty", "Approved entities only"],["05", "Execution", "Pre-transaction verification"],["06", "Audit", "Every decision traceable"]];

function VaultCard({ kind }: { kind: "btcvp" | "btcvc" }) {
  const vp = kind === "btcvp";
  return <a className={`vault-card ${vp ? "vault-teal" : "vault-brand"}`} href={`/${kind}`}><div className="vault-card-head"><span className="token-orb">₿<i>{vp ? "P" : "C"}</i></span><span className="verified-chip">✓ VETA VERIFIED</span><Arrow diagonal /></div><div className="vault-card-copy"><span className="eyebrow">{vp ? "PROOF-OF-ASSET" : "INSTITUTIONAL CUSTODY"}</span><h3>{vp ? "BTCvp" : "BTCvc"}</h3><p>{vp ? "AI-coordinated market-neutral BTC yield with policy-bound execution." : "Qualified custody and single-venue basis yield for verified participants."}</p></div><div className="vault-card-metrics"><div><small>Target APY</small><strong>{vp ? "6.55%" : "2–8.5%"}</strong></div><div><small>Network</small><strong>Pharos</strong></div><div><small>BTC backing</small><strong>1 : 1</strong></div></div><div className="vault-card-line"><i /><span>{vp ? "410.00186448 BTCVP" : "11 BTCVC"}</span></div></a>;
}

export function LandingPage() {
  return <main className="site-shell"><SiteHeader />
    <section className="hero"><div className="hero-aura" /><div className="hero-copy"><div className="release-pill"><span /> NARO COORDINATOR v1.4 — LIVE</div><h1>Bluechip assets.<br /><em>Optimized by AI.</em><br />Bound by mandate.</h1><p>Naro continuously compares risk-adjusted APY across approved DeFi venues, reallocating bluechip assets when a better opportunity clears Ciara&apos;s mandate. Veta verifies every movement before execution. Bitcoin is the first live deployment.</p><div className="hero-actions"><a className="primary-action" href="/vaults">Explore live vaults <Arrow /></a><a className="secondary-action" href="#controls">View control stack <Arrow diagonal /></a></div><div className="hero-proof"><span><i className="proof-green">✓</i> Bluechip mandates</span><span><i>◇</i> Cross-protocol optimization</span><span><i>⌁</i> Verifiable execution</span></div></div><AgentCore /></section>
    <section className="metric-rail" aria-label="Protocol metrics"><div><small>CAPITAL COORDINATED</small><strong>$33.38M</strong><span>Live vault supply</span></div><div><small>BLUECHIP COVERAGE</small><strong>BTC</strong><span>First asset · more to follow</span></div><div><small>CONTROL LAYER</small><strong>VETA</strong><span><i className="live-dot" /> Enforcing</span></div><div><small>SETTLEMENT</small><strong>PHAROS</strong><span>Pacific · Atlantic</span></div></section>
    <section className="narrative-section" id="intelligence"><div className="section-kicker"><span>01</span> INTELLIGENCE, WITH BOUNDARIES</div><div className="section-heading split-heading"><h2>Autonomous enough<br />to capture opportunity.</h2><div><h2><em>Constrained enough</em><br />to protect capital.</h2><p>Naro does not replace the rules. It makes the vault responsive inside them.</p></div></div><div className="operating-stack"><article><div className="stack-icon ciara-icon">C</div><span className="eyebrow">01 / CURATION LAYER</span><h3>Ciara defines</h3><p>Approved strategies, allocations, counterparties and risk parameters become a machine-readable mandate.</p><ul><li>Strategy allowlist</li><li>Risk budgets</li><li>Liquidity rules</li></ul></article><div className="stack-flow"><span>MANDATE</span><i /><Arrow /></div><article className="featured-stack"><div className="stack-icon naro-icon"><svg viewBox="0 0 28 28"><path d="M5 21V7l9 9 9-9v14M5 7l9-4 9 4" fill="none" stroke="currentColor" strokeWidth="1.8" /></svg></div><span className="eyebrow">02 / COORDINATION LAYER</span><h3>Naro coordinates</h3><p>Continuous observation turns market conditions, exposures and redemption needs into bounded actions.</p><ul><li>24/7 monitoring</li><li>Allocation proposals</li><li>Automated de-risking</li></ul></article><div className="stack-flow"><span>PROPOSAL</span><i /><Arrow /></div><article><div className="stack-icon veta-icon">✓</div><span className="eyebrow">03 / CONTROL LAYER</span><h3>Veta verifies</h3><p>Every proposed movement is checked against the mandate before execution, settlement and audit.</p><ul><li>Pre-execution checks</li><li>Policy enforcement</li><li>Auditable records</li></ul></article></div></section>
    <section className="vault-showcase" id="vaults"><div className="section-kicker"><span>02</span> FIRST BLUECHIP DEPLOYMENT · LIVE VAULTS</div><div className="section-heading row-heading"><h2>Bitcoin is where Naro starts.<br /><em>Not where it stops.</em></h2><p>The first Naro vaults apply the shared AI coordination and verification stack to Bitcoin. Future bluechip assets can plug into the same mandate-bound runtime.</p></div><div className="vault-grid"><VaultCard kind="btcvp" /><VaultCard kind="btcvc" /></div><a className="text-link" href="/vaults">Compare vault architecture <Arrow /></a></section>
    <section className="control-section" id="controls"><div className="control-intro"><div className="section-kicker"><span>03</span> POLICY-BOUND EXECUTION</div><h2>AI that can act.<br /><em>Never outside the rules.</em></h2><p>Each action passes through a deterministic control boundary. If a proposal violates the mandate, capital does not move.</p><div className="blocked-action"><div><span className="blocked-mark">×</span><span><b>Execution blocked</b><small>Proposed leverage 2.8× exceeds 2.0× limit</small></span></div><span>VETA · 02:08:41</span></div></div><div className="control-matrix"><div className="matrix-head"><span>CONTROL</span><span>ENFORCEMENT</span><span>STATUS</span></div>{controls.map(([id, name, rule]) => <div className="matrix-row" key={id}><span>{id}</span><b>{name}</b><span>{rule}</span><i>ENFORCED</i></div>)}</div></section>
    <section className="transparency-section" id="transparency"><div className="section-kicker"><span>04</span> RADICAL TRANSPARENCY</div><div className="transparency-grid"><div><h2>Every decision leaves<br />a verifiable trace.</h2><p>See what Naro observed, what it proposed, which policy checks passed and when capital moved.</p><a className="secondary-action" href="/btcvp">Open live vault <Arrow diagonal /></a></div><div className="audit-terminal"><div className="terminal-head"><span><i /><i /><i /></span><b>EXECUTION TRACE</b><span>LIVE</span></div><div className="terminal-row"><time>02:14:08</time><span className="log-green">PASS</span><p>Rebalance BTCvp allocation +3.2%</p><small>tx_8a1...c44</small></div><div className="terminal-row"><time>02:08:41</time><span className="log-red">BLOCK</span><p>Leverage proposal above mandate</p><small>pol_12...f09</small></div><div className="terminal-row"><time>01:52:17</time><span className="log-green">PASS</span><p>Liquidity reserve restored to 14.0%</p><small>tx_79c...2e1</small></div><div className="terminal-row"><time>01:31:02</time><span className="log-neutral">SCAN</span><p>18 venues · 42 market signals</p><small>obs_31...119</small></div><div className="terminal-foot"><span className="live-dot" /> Listening for verified events…</div></div></div></section>
    <section className="closing-cta"><div className="cta-orbit" /><span className="eyebrow">THE CONTROLLED PATH TO AUTONOMOUS CAPITAL</span><h2>Put bluechip assets to work.<br /><em>Keep the mandate in control.</em></h2><a className="primary-action" href="/vaults">Explore the first BTC vaults <Arrow /></a></section>
    <footer><NaroMark /><p>AI-coordinated bluechip vaults. Mandate-bound execution.</p><div><a href="/vaults">Vaults</a><a href="#controls">Controls</a><a href="#transparency">Transparency</a></div><span>© 2026 Naro · VishwaLab</span></footer>
  </main>;
}

type VaultKind = "btcvp" | "btcvc";

const vaultData = {
  btcvp: {
    symbol: "BTCvp", subtitle: "AI-coordinated proof-of-asset vault", eyebrow: "PROOF-OF-ASSET · MARKET NEUTRAL", apy: "6.55%", supply: "410.00186448 BTCVP", usd: "$32.51M", launch: "10 June 2026", id: "0x79D154…a330BB", tone: "teal", access: "Open access", strategy: "Market-neutral / delta-neutral", rewards: "Accrues to redemption NAV",
    description: "BTCvp gives users native BTC exposure while Naro coordinates market-neutral yield. Ciara defines the strategy mandate. Veta verifies every capital movement before execution.",
    chart: "18,119 32,106 46,101 61,90 76,86 91,68 106,64 121,53 136,45 151,41 166,25 181,18 196,12 211,8",
    faq: [
      ["What is BTCVP?", "BTCVP is a BTC-backed proof-of-asset token on Pharos, minted against native BTC and recorded on-chain. It is a non-rebasing, yield-accruing token that maintains BTC exposure while participating in guardrailed, AI-coordinated yield strategies. Every capital movement is verified by Veta before execution."],
      ["What are Naro, Ciara, and Veta?", "Ciara defines the approved strategies, allocation frameworks and risk parameters. Naro monitors positions, liquidity and market conditions and coordinates actions within those rules. Veta independently verifies every capital movement against the rules before execution."],
      ["Why is BTCVP different?", "Most BTC yield products focus on generating yield. BTCVP focuses on how yield is generated: AI-assisted coordination, curated strategy frameworks and deterministic execution controls. Capital can be actively managed, but cannot move outside predefined constraints."],
      ["Where is my BTC held?", "Your BTC is never wrapped or bridged. Native BTC remains held in custody and backed by real BTC throughout the lifecycle of BTCVP. Yield accrues to BTCVP’s redemption value rather than through token rebasing."],
      ["How is yield generated?", "Yield is generated through institutional market-neutral and delta-neutral strategies coordinated by Naro and settlement partners. These may include hedged arbitrage, funding-rate capture, liquidity deployment and other approved, risk-managed opportunities."],
      ["What does the AI coordinator do — and what can't it do?", "Naro monitors positions, exposure, market conditions, liquidity, margin and redemption needs, then proposes allocation, rebalancing, routing and de-risking actions. It cannot move capital on its own. Veta must verify every action against the mandate."],
      ["Who controls the vault?", "BTCVP uses layered control. Ciara defines the strategy and risk framework, Naro coordinates operations inside it, and Veta verifies every movement. Administrative controls remain subject to approved governance and operational procedures."],
      ["How is liquidation risk managed?", "Market-neutral and delta-neutral strategies reduce directional exposure. Leverage, venue, counterparty, liquidity and risk limits are enforced on every action, while Naro continuously monitors positions and can de-risk at predefined thresholds."],
      ["How does the deposit work?", "Deposit through this interface from a Bitcoin wallet you control. The interface associates the deposit with your connected Pharos address. After 6 Bitcoin confirmations, the deposit is detected and BTCVP is minted to your Pharos wallet."],
      ["Can I deposit from an exchange?", "No. Exchange withdrawals may not contain the routing information required to associate the deposit with your Pharos address and may require manual recovery."],
      ["How do I redeem my BTC?", "Choose Redeem, connect your Pharos wallet, enter the BTCVP amount and provide a Bitcoin receiving address. BTCVP is burned and native BTC is released after the redemption passes the required checks."],
      ["Do I need two wallets?", "Yes. Use a Pharos-compatible wallet to receive and manage BTCVP, and a Bitcoin wallet you control to send deposits and receive redeemed BTC."],
      ["How long does it take?", "Minting typically completes after 6 Bitcoin confirmations, usually around 60 minutes. Redemption timing depends on network and custody processing conditions."],
      ["Why might my redeemed BTC differ?", "BTCVP is non-rebasing. Its redemption value can reflect accrued strategy yield, realized performance and applicable operational costs rather than remaining fixed to the token quantity alone."],
    ],
  },
  btcvc: {
    symbol: "BTCvc", subtitle: "Institutional custody vault", eyebrow: "QUALIFIED CUSTODY · BASIS YIELD", apy: "2–8.5%", supply: "11 BTCVC", usd: "$871.86K", launch: "17 July 2026", id: "0x4b0143…77ee3d", tone: "brand", access: "KYB / KYC", strategy: "Single-venue basis arbitrage", rewards: "Monthly BTCvc airdrop",
    description: "Qualified custody. Fully reserved assets. Verifiable execution controls. Naro coordinates a simple institutional basis strategy within a curator-defined mandate.",
    chart: "18,114 32,110 46,99 61,93 76,82 91,77 106,65 121,56 136,50 151,36 166,31 181,21 196,16 211,10",
    faq: [
      ["What is BTCvc?", "BTCvc is a BTC-backed proof-of-asset token minted against native BTC and available across supported networks, including Pharos and Sui. It is a non-rebasing BTC representation designed for participation in institutional BTC yield strategies."],
      ["What are Naro, Ciara, and Veta?", "Ciara defines approved strategies and operational parameters. Naro monitors market conditions, liquidity and approved opportunities. Veta independently verifies every capital movement against predefined constraints before execution."],
      ["Why is BTCvc different?", "BTCvc combines AI-assisted coordination, institutional custody, curated strategy frameworks and execution controls. Capital can be actively coordinated, but cannot move outside predefined constraints."],
      ["Where is my BTC held?", "Your BTC is never wrapped or bridged. Native BTC remains with a qualified institutional custodian and BTCvc remains fully backed throughout its lifecycle."],
      ["How is yield generated?", "The current strategy focuses on institutional single-venue basis arbitrage. It is intentionally simple and transparent, designed to generate BTC-denominated returns inside a controlled risk framework."],
      ["How are rewards distributed?", "BTCvc is non-rebasing. At the end of each calendar month, a snapshot is taken and holders receive BTCvc rewards by airdrop, proportional to their holdings at the snapshot."],
      ["What does the AI coordinator do — and what can't it do?", "Naro monitors approved strategy execution, custody status, liquidity and operational conditions. It cannot move capital independently; every movement must satisfy Ciara’s framework and be verified by Veta."],
      ["Who controls BTCvc?", "Ciara defines the operating framework, Naro coordinates the approved strategy, and Veta enforces the framework. Assets remain subject to qualified custody and approved governance procedures."],
      ["How is risk managed?", "Strategy, venue, counterparty, custody, liquidity and execution limits are encoded in the mandate. Naro monitors conditions continuously and Veta blocks actions that fall outside those limits."],
      ["How does the deposit work?", "Connect your Pharos wallet, complete the required KYB/KYC checks and deposit from a Bitcoin wallet you control. After the required confirmations, BTCvc is minted to the associated address."],
      ["Can I deposit from an exchange?", "No. Deposit from a Bitcoin wallet you control so the routing information can correctly associate the deposit with your Pharos address."],
      ["Is there a lock-up period?", "The current institutional strategy uses a defined reward period. Eligibility and redemption timing are shown before confirmation and remain subject to the active vault terms."],
      ["How do I redeem my BTC?", "Choose Redeem, connect the eligible Pharos wallet, enter the BTCvc amount and provide a Bitcoin receiving address. Redemption is processed after policy, eligibility and custody checks."],
      ["Do I need two wallets?", "Yes. A Pharos-compatible wallet holds BTCvc, while a Bitcoin wallet you control is used for deposits and native BTC redemption."],
      ["How long does it take?", "Minting typically follows 6 Bitcoin confirmations, usually around 60 minutes. Institutional verification and redemption windows may add processing time."],
      ["When do rewards begin accruing?", "Reward eligibility begins after a successful mint and is determined by the balance recorded for the active monthly snapshot period."],
      ["What asset is the monthly airdrop paid in?", "Monthly rewards are paid in BTCvc and distributed automatically to eligible wallets based on their snapshot balance."],
      ["Can I transfer BTCvc during the lock-up period?", "BTCvc can be transferred where supported, but moving it before the monthly snapshot can change reward eligibility for the sending and receiving wallets."],
    ],
  },
} as const;

function AppFooter() {
  return <footer className="app-footer"><NaroMark /><p>AI-coordinated bluechip vaults. Mandate-bound execution.</p><div><a href="/">Home</a><a href="/vaults">Vaults</a><a href="/#controls">Controls</a></div><span>© 2026 Naro · VishwaLab</span></footer>;
}

export function VaultsIndex() {
  return <main className="site-shell app-shell"><SiteHeader compact /><section className="vault-index-hero"><div><div className="section-kicker"><span>VAULT DIRECTORY</span> VERIFIED STRATEGIES</div><h1>Choose the rules<br /><em>your Bitcoin runs on.</em></h1></div><p>Naro vaults share the same coordination and verification stack. Their custody, eligibility and reward mechanics are deliberately different.</p></section><section className="vault-index-grid"><VaultCard kind="btcvp" /><VaultCard kind="btcvc" /></section><section className="compare-panel"><div className="compare-title"><span>Compare architecture</span><span>BTCvp</span><span>BTCvc</span></div>{[["Target APY","6.55%","2–8.5%"],["Custody model","Native BTC custody","Qualified institutional custody"],["Access","Open access","KYB / KYC"],["Primary strategy","Market / delta-neutral","Single-venue basis"],["Reward mechanics","Accruing redemption NAV","Monthly BTCvc airdrop"],["Control layer","Veta verified","Veta verified"],["Settlement","Pharos Pacific / Atlantic","Pharos Pacific / Atlantic"]].map(row=><div className="compare-row" key={row[0]}><b>{row[0]}</b><span>{row[1]}</span><span>{row[2]}</span></div>)}</section><AppFooter /></main>;
}

function YieldChart({ tone, points, period, setPeriod }: { tone: string; points: string; period: string; setPeriod: (v:string)=>void }) {
  return <div className={`yield-chart tone-${tone}`}><div className="chart-head"><div><small>HISTORICAL NET APY</small><strong>{period === "7D" ? "3.15%" : period === "30D" ? "3.87%" : "6.55%"}</strong><span>+0.18% this period</span></div><div>{["7D","30D","1Y"].map(p=><button key={p} className={period===p?"active":""} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div><svg viewBox="0 0 230 130" preserveAspectRatio="none" aria-label="Cumulative yield chart"><defs><linearGradient id={`chart-${tone}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="currentColor" stopOpacity=".28"/><stop offset="1" stopColor="currentColor" stopOpacity="0"/></linearGradient></defs><path className="chart-grid" d="M0 20H230M0 55H230M0 90H230M0 125H230"/><polygon points={`${points} 211,128 18,128`} fill={`url(#chart-${tone})`}/><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/><circle cx="211" cy={tone==="teal"?"8":"10"} r="3" fill="currentColor"/></svg><div className="chart-axis"><span>Aug 17</span><span>Aug 19</span><span>Aug 21</span><span>Aug 24</span></div></div>;
}

function CoordinatorPanel({ kind }: { kind: VaultKind }) {
  const vp=kind==="btcvp";
  return <div className="coordinator-panel"><div className="coordinator-head"><span className="naro-mini"><i />N</span><div><b>Naro coordinator</b><small><i className="live-dot" /> LIVE · monitoring this vault</small></div><span>MODEL 1.4</span></div><div className="agent-observation"><span>OBSERVING</span><b>{vp?"Funding spread above 30D mean":"Basis curve within target range"}</b><div className="micro-line"><i/><i/><i/><i/><i/><i/><i/></div><small>{vp?"18 signals · 6 venues":"12 signals · 1 approved venue"}</small></div><div className="agent-proposal"><span>LAST VERIFIED ACTION</span><b>{vp?"Liquidity reserve +1.8%":"Monthly position roll"}</b><p><i>Ciara</i><em>→</em><i>Naro</i><em>→</em><i className="approved">✓ Veta</i></p><small>{vp?"18m ago · tx_8a1…c44":"3h ago · tx_39e…b17"}</small></div></div>;
}

function TransactionPanel({ kind }: { kind: VaultKind }) {
  const d=vaultData[kind]; const [mode,setMode]=useState<"Mint"|"Redeem">("Mint"); const [amount,setAmount]=useState(""); const [wallet,setWallet]=useState(false); const [network,setNetwork]=useState("Pharos Pacific · 1672");
  return <aside className="transaction-panel"><div className="transaction-tabs"><button className={mode==="Mint"?"active":""} onClick={()=>setMode("Mint")}>Mint</button><button className={mode==="Redeem"?"active":""} onClick={()=>setMode("Redeem")}>Redeem</button><select aria-label="Destination network" value={network} onChange={e=>setNetwork(e.target.value)}><option>Pharos Pacific · 1672</option><option>Pharos Atlantic · 688689</option></select></div><div className="asset-input"><label>From <span>Balance: 0.00000000</span></label><div><span className="asset-pill">{mode==="Mint"?"₿ BTC":d.symbol}</span><input aria-label="From amount" value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9.]/g,""))} inputMode="decimal" placeholder="0.00"/><button onClick={()=>setAmount("0.00")}>MAX</button></div><small>Min: 0.0001 {mode==="Mint"?"BTC":d.symbol}</small></div><div className="swap-marker">↓</div><div className="asset-input"><label>To <span>≈ 1:1 · 8 dp</span></label><div><span className="asset-pill">{mode==="Mint"?d.symbol:"₿ BTC"}</span><output>{amount||"0.00"}</output></div><small>Balance: 0</small></div><div className="receiving-row"><span>Receiving address ⓘ</span><button onClick={()=>setWallet(true)}>{wallet?"0x91F2…B470":"Connect Pharos wallet"}</button></div><button className="connect-primary" onClick={()=>setWallet(true)}>{wallet?`${mode} ${amount||"0.00"} ${mode==="Mint"?"BTC":d.symbol}`:"Connect Bitcoin wallet"}</button>{wallet&&<div className="success-state"><span>✓</span><p><b>Wallets ready</b><small>Review the amount and destination before execution.</small></p></div>}<p className="custody-note">Deposits are sent from your connected wallet to custody <b>{kind==="btcvp"?"tb1q9ycp…9jf8x0":"tb1qxvw0…m0zrvs"}</b></p><div className="warning-note">⚠ Deposit through this interface from a wallet you control. Do not send BTC directly from an exchange.</div></aside>;
}

function FAQ({ items }: { items: readonly (readonly [string,string])[] }) {
  const [open,setOpen]=useState<number|null>(0); return <section className="faq-section"><div className="section-kicker"><span>05</span> VAULT KNOWLEDGE</div><h2>Understand before<br />capital moves.</h2><div className="faq-list">{items.map(([q,a],i)=><article className={open===i?"open":""} key={q}><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}><span>{String(i+1).padStart(2,"0")}</span><b>{q}</b><i>{open===i?"−":"＋"}</i></button>{open===i&&<p>{a}</p>}</article>)}</div></section>;
}

export function VaultDetail({ kind }: { kind: VaultKind }) {
  const d=vaultData[kind]; const [period,setPeriod]=useState("7D");
  return <main className={`site-shell app-shell vault-detail ${d.tone}`}><SiteHeader compact /><section className="vault-breadcrumb"><a href="/vaults">Vaults</a><span>/</span><b>{d.symbol}</b><i className="live-dot" /> LIVE</section><section className="vault-overview"><div className="vault-title-block"><div className="title-token">₿<i>{kind==="btcvp"?"P":"C"}</i></div><div><span className="verified-chip">✓ VERIFIED BY VETA</span><h1>{d.symbol}</h1><p>{d.subtitle}</p></div></div><div className="vault-summary"><span>TARGET APY</span><strong>{d.apy}</strong><small>Net of strategy fees</small></div><p className="vault-description">{d.description}</p><div className="overview-facts"><div><span>DESTINATION NETWORK</span><b>Pharos Pacific</b></div><div><span>CONFIRMATION</span><b>Typically ~60 min</b></div><div><span>DEPLOYED</span><b>{d.launch}</b></div><div><span>VAULT ID</span><b>{d.id}</b></div></div></section><section className="vault-live-grid"><div className="vault-data-column"><CoordinatorPanel kind={kind}/><div className="vault-stat-row"><div><span>CURRENT RATIO</span><b>1 {d.symbol} = 1 BTC</b></div><div><span>TOTAL SUPPLY</span><b>{d.supply}</b><small>{d.usd}</small></div><div><span>ACCESS</span><b>{d.access}</b></div></div><YieldChart tone={d.tone} points={d.chart} period={period} setPeriod={setPeriod}/><div className="mandate-grid"><article><span>ACTIVE STRATEGY</span><h3>{d.strategy}</h3><p>Coordinator monitors market structure, exposure and liquidity continuously.</p></article><article><span>REWARD MECHANIC</span><h3>{d.rewards}</h3><p>Non-rebasing accounting keeps the vault mechanics transparent.</p></article><article className="mandate-status"><span>CONTROL STATUS</span><h3><i className="live-dot" /> All policies enforced</h3><p>Allocation · leverage · venue · liquidity · counterparty</p></article></div></div><TransactionPanel kind={kind}/></section><section className="activity-section"><div><span>YOUR {d.symbol.toUpperCase()} ACTIVITY</span><h2>Wallet activity</h2><p>Mints and redemptions for your connected Pharos wallet on Pharos Pacific.</p></div><div className="empty-activity"><span>⌁</span><b>No wallet connected</b><small>Connect your Pharos wallet to view transaction history.</small><button>Connect Pharos wallet</button></div></section><FAQ items={d.faq}/><AppFooter /></main>;
}
